### ISSUE TITLE
E-mail for Data Processing and Feature Engineering Code

### ISSUE THREAD

**Issue by YeeHoming1024** [DariusRoman/Machine-learning-pipeline-for-battery-state-of-health-estimation#2]
Hello, I have read your paper and your work is really outstanding. I have sent e-mail to your count--dvr1@hw.ac.uk for the data processing and feature engineering code, but I have not received your reply and I wonder if there is something wrong. If you see this message, please take the time to help, I promise that the code will only be used for scientific research. My e-mail address is homing.yee@qq.com and I am looking forward to your reply. Thank you for your time.

**Comment by DariusRoman** [comment]
Hey @YeeHoming1024 I no longer have access to that email. Please email me at darius.roman@outlook.com

**Comment by DariusRoman** [comment]
You cannot contact me through issues. This is code specific please. Thank you.
